; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:waveshare_esp32_s3_zero]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
monitor_filters = direct
board = waveshare_esp32_s3_zero
; build_flags = 
;   -DCONFIG_ESP_COREDUMP_ENABLE=0

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
